### ISSUE TITLE
ActionController::UrlGenerationError: No route matches...missing required keys: [:id]

### ISSUE THREAD

**Issue by ThuyNT13** [ThuyNT13/rails_template#1]
```bash
Error:
UsersEditTest#test_successful_edit:
ActionController::UrlGenerationError: No route matches {:action=>"edit", :controller=>"users", :id=>nil}, missing required keys: [:id]
    test/integration/users_edit_test.rb:31:in `block in <class:UsersEditTest>'

bin/rails test test/integration/users_edit_test.rb:26
```
Possibly issues with how I wrote the [UsersEditTest](https://github.com/ThuyNT13/rails_template/blob/master/test/integration/users_edit_test.rb) as there is no error when `get edit_user_path(@suser)` is invoked the first time at line 12 as opposed to line 31:

```ruby
require 'test_helper'

class UsersEditTest < ActionDispatch::IntegrationTest

  def setup
    @user = users(:user1)
  end

  test "unsuccessful edit" do
    login_as(@user)
    assert is_logged_in?
    get edit_user_path(@user)
    assert_template 'users/edit'
    assert_select "title", head_title("Edit user")
    patch user_path(@user), params: { user: {
      username: '',
      email: '@email.com',
      password: '123456',
      password_confirmation: '654321'
    }}
    assert_select 'div.alert-danger'
    assert_select 'div#error_explanation'
    assert_template 'users/edit'
  end

  test "successful edit" do
    login_as(@user)
    assert is_logged_in?
    # FIXME users#edit no route matches, missing required [:id] keys
    # works fine above, line 12
    get edit_user_path(@suser)
    assert_template 'users/edit'
    usernameEdit = "foo"
    emailEdit = "foo@bar.com"
    patch user_path(@user), params: { user: {
      username: usernameEdit,
      email: emailEdit,
      password: "123456",
      password_confirmation: "123456"
      }}
      assert_not flash.empty?
      @user.reload
      assert_equal usernameEdit, @user.username
      assert_equal emailEdit, @user.email
    end
end
```
[routes](https://github.com/ThuyNT13/rails_template/blob/master/config/routes.rb) for users: 

```ruby
   Prefix Verb   URI Pattern               Controller#Action

   signup GET    /signup(.:format)         users#new
          POST   /signup(.:format)         users#create
    users GET    /users(.:format)          users#index
          POST   /users(.:format)          users#create
 new_user GET    /users/new(.:format)      users#new
edit_user GET    /users/:id/edit(.:format) users#edit
     user GET    /users/:id(.:format)      users#show
          PATCH  /users/:id(.:format)      users#update
          PUT    /users/:id(.:format)      users#update
          DELETE /users/:id(.:format)      users#destroy

```
[UsersController](https://github.com/ThuyNT13/rails_template/blob/master/test/controllers/users_controller_test.rb):
```ruby
class UsersController < ApplicationController
  before_action :set_user, except: [:index, :new, :create, :user_params]
...
  def show
  end
...
  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      render 'edit'
    end
  end
...
  private

  def set_user
    @user = User.find(params[:id])
  end
...
```

`link_to` from partial [_header.html.erb](https://github.com/ThuyNT13/rails_template/blob/master/app/views/layouts/_header.html.erb)  (haven't tested current_user, yet):

```html
...
<li><%= link_to "Profile", current_user %></li>
<li><%= link_to "Settings", edit_user_path(current_user) %></li>
...
```
`current_user` code from [SessionsHelper](https://github.com/ThuyNT13/rails_template/blob/master/app/helpers/sessions_helper.rb):

```ruby
module SessionsHelper
...
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
...
```
more similar errors from [users_controller_test.rb](https://github.com/ThuyNT13/rails_template/blob/master/test/controllers/users_controller_test.rb)  for  `users#show` and `users#edit`

```bash
Error:
UsersControllerTest#test_should_get_show_routes:
ActionController::UrlGenerationError: No route matches {:action=>"show", :controller=>"users", :id=>nil}, missing required keys: [:id]
    test/controllers/users_controller_test.rb:25:in `block in <class:UsersControllerTest>'

bin/rails test test/controllers/users_controller_test.rb:24

Error:
UsersControllerTest#test_should_get_edit_routes:
ActionController::UrlGenerationError: No route matches {:action=>"edit", :controller=>"users", :id=>nil}, missing required keys: [:id]
    test/controllers/users_controller_test.rb:30:in `block in <class:UsersControllerTest>'

bin/rails test test/controllers/users_controller_test.rb:24
```

**Comment by ThuyNT13** [comment]
typo on line 31, `@suser` in spec; extra "s". So likely others are typos, too.
